# Generated by Django 3.0.5 on 2020-04-29 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT NAME', max_length=50, verbose_name="tile's name")),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=500, verbose_name="tile's description")),
                ('to_e', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tile_to_e', to='adventure.Tile', verbose_name='tile to the east')),
                ('to_n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tile_to_n', to='adventure.Tile', verbose_name='tile to the north')),
                ('to_s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tile_to_s', to='adventure.Tile', verbose_name='tile to the south')),
                ('to_w', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tile_to_w', to='adventure.Tile', verbose_name='tile to the west')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="player's uuid")),
                ('current_tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.Tile', verbose_name="player's current tile")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="player's user")),
            ],
        ),
    ]
